demonstration_configs:
- domain_randomization: &id001
    cameras:
      config_path: /cpfs/user/zhuzihou/dev/scenario-forge/docs/records/evidence/2026-07-05-phase11-small-multi-task-canary/soap_to_dish_phase11_4_top_camera_retake.yml
      type: fixed
    random_environment:
      has_wall: false
      hdr: false
      robot_base_position: false
      robot_eepose: false
      table_texture: false
      table_type: false
      wall_texture: false
    rewrite_instruction: false
  generation_config:
    action_path:
      mode: auto
      robot: 0
    articulation: []
    goal:
    - - obj1_uid:
        - '0'
        obj2_uid:
        - '1'
        position:
        - top
        fixed_position: true
        allow_fixed_grasp: true
        force_fixed_grasp: true
        gripper_rot_config:
          axis: z
          angle: 90
          apply_in_relative_grasp: true
          compensate_obj1_yaw: true
        arm: auto
        grasp_idx:
        - 0
        - 1
        - 2
        - 3
        - 4
        base_motion_list:
          0:
          - x: null
            y:
            - -0.05
            - 0.05
            yaw: null
            type: align
          - x: 0.2
            y: 0.0
            yaw: 0.0
            type: delta
          3:
          - x: null
            y:
            - -0.05
            - 0.05
            yaw: null
            type: align
    mode: manual
    planner: curobo
  instruction: Pick up the bar of soap from the bathtub edge and place it into the
    soap dish.
  layout_config:
    type: random_custom_tableset
    in_order: true
    custom_tableset:
      '0':
        random_range_x: -0.35
        random_range_y: -0.2
        random_range_w: 0.2
        random_range_h: 0.2
        random_range_angle: 15
        additional_height: 0.02
        buffer_size: 0.05
        type: global_range
      '1':
        type: centric_range
        angle_bilateral: true
        angle: 15
        w: 0.06
        h: 0.06
        buffer_size: 0.0
      '2':
        type: centric_range
        angle_bilateral: true
        angle: 15
        w: 0.06
        h: 0.06
        buffer_size: 0.0
  mode: manual
  num_episode: 400
  object_config:
    '0':
      type: load_object_from_path
      filter_rule: []
      max_cached_num: 10
      path: regex:^object_usds/custom_usd/ebench_usds/soap/ready/.*\.usd$
      relative_scale: 1
      option:
      - plain_replace
      without_colliders: false
    '1':
      type: existed_object
      uid_list:
      - _01
    '2':
      type: existed_object
      uid_list:
      - _06
  preprocess_config: []
  robots:
  - &id002
    type: manip/lift2/R5a
    position:
    - -1.02
    - 0.0
    - 0.31
  table_uid: table
  task_name: ebench/mobile_manip/soap_to_dish_test_mini
  usd_name: scene_usds/ebench/simple_pnp/task3/scene
  env_vars:
    MDL_SYSTEM_PATH: /isaac-sim/materials/:{ASSETS_DIR}/miscs/mdl/ebench/mdl:{ASSETS_DIR}/scene_usds/ebench/simple_pnp/task3/SubUSDs/materials
evaluation_configs:
- domain_randomization: *id001
  num_test: 20
  num_steps: 1000
  robots:
  - *id002
  table_uid: table
  task_name: ebench/mobile_manip/soap_to_dish_test_mini
  usd_name: scene_usds/ebench/simple_pnp/task3/scene
  env_vars:
    MDL_SYSTEM_PATH: /isaac-sim/materials/:{ASSETS_DIR}/miscs/mdl/ebench/mdl:{ASSETS_DIR}/scene_usds/ebench/simple_pnp/task3/SubUSDs/materials
